### PR TITLE
Adapt ludwig to handle ADPA 93

### PR DESCRIPTION
**Pull request by fpagnoux**
Connected to sgmap/mes-aides-ui#147

### CODE REVIEW

**Comment by MattiSG** [comment]
`testableQuantities` is IMO misleading, as it implies an enumerable “quantity”, while it could also be a `Boolean`, for example. What made `possibleValues` problematic to you?

As for `testItem`, it is indeed better than the Mes Aides-specific `droit`, but doesn't quite give an idea what it _is_, and might be misleading as the operational domain of Ludwig is tests, yet these elements are actually descriptions from the Ludwig _client’s_ domain. The best alternative I could provide right now is `entity`.

---

Naming this kind of very generic concepts is very tricky, yet very important. To be fully honest, I'm not sure it is the right time to do such refactors, as it should probably be the result of a half day domain workshop, and especially considering they will dripple on all Ludwig clients.

**Comment by fpagnoux** [comment]
I admit I probably got too much enthusiastic with the renaming, but the initial naming made me upset :disappointed: 

I find `possibleValues` really non explicit: values makes me think about the numeric values of the quantities we are testing. I don't see where a description of a quantity we can test is a value, and this term is also super generic. 
As for testableQuantities, a boolean quantity doesn't seem odd to me.

But let's keep this discussion for the domain workshop to come :)

**Comment by fpagnoux** [comment]
Renaming will be discussed later.

**Comment by MattiSG** [comment]
> values makes me think about the numeric values of the quantities we are testing

Interesting!!

But therefore definitely not something to change lightly considering the non-trivial discussions brought up  :)

**Pull request closed without merging**
